DROP SEQUENCE BBS_SEQ;
CREATE SEQUENCE BBS_SEQ NOCACHE;

DROP TABLE BBS;
CREATE TABLE BBS (
    BBS_NO NUMBER NOT NULL,
    ID VARCHAR2(30 BYTE) NOT NULL,
    TITLE  VARCHAR2(1000 BYTE) NOT NULL,  -- 제목이 곧 내용
    CREATE_DATE DATE NOT NULL,
    STATE  NUMBER(1) NOT NULL,  /* 정상:1, 삭제:0 */
    DEPTH  NUMBER(2) NOT NULL,  /* 원글:0, 1차댓글:1, 2차댓글:2, ... */
    GROUP_NO NUMBER NOT NULL,  /* 원글과 모든 댓글은 같은 GROUP_NO, 원글:BBS_NO, 댓글:원글의 BBS_NO */
    GROUP_ORDER NUMBER NOT NULL,  /* 동일 그룹 내 표시 순서 */
    BBS_LAST_MODIFY_DATE DATE NOT NULL,
    IP VARCHAR2(30 BYTE) NOT NULL,
    CONSTRAINT PK_BBS PRIMARY KEY(BBS_NO)
);
-- 댓글 외래키 : 회원이 탈퇴하면 댓글도 삭제한다.
ALTER TABLE BBS
    ADD CONSTRAINT FK_BBS
        FOREIGN KEY(ID) REFERENCES USERS(ID)
            ON DELETE CASCADE;