use lji170;

DROP TABLE IF EXISTS COUPON_USE;
DROP TABLE IF EXISTS COUPON;
DROP TABLE IF EXISTS ALARM;


-- 이용권 (삭제순서 : 결제 -> 이용권(PASS))
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS PAYMENT_LOG;
DROP TABLE IF EXISTS PASS;

DROP TABLE IF EXISTS MUSIC_LIKE;
DROP TABLE IF EXISTS MUSIC_COMMENT;
DROP TABLE IF EXISTS MY_MUSIC;
DROP TABLE IF EXISTS PLAYLIST;
DROP TABLE IF EXISTS ACTIVE_LOG;

-- 뮤직 (삭제순서 : 코멘트/좋아요 -> 뮤직)
DROP TABLE IF EXISTS  MUSIC_COMMENT;
DROP TABLE IF EXISTS  MUSIC_LIKE;
DROP TABLE IF EXISTS MUSIC;

-- 관리자 (공지사항, FAQ)
DROP TABLE IF EXISTS SUMMERNOTE_IMAGE;
DROP TABLE IF EXISTS ATTACH;
DROP TABLE IF EXISTS UPLOAD;
DROP TABLE IF EXISTS BOARD;

-- 관리자 (챗)
DROP TABLE IF exists CHAT_ADMIN;

-- 유저 (삭제순서 : 프로필/로그/ -> 유저/탈퇴/휴면)
DROP TABLE IF EXISTS PROFILEIMAGE;
DROP TABLE IF EXISTS ACCESS_LOG;
DROP TABLE IF EXISTS RETIRE_USERS;
DROP TABLE IF EXISTS SLEEP_USERS;
DROP TABLE IF EXISTS USERS;








-- 테이블 생성
CREATE TABLE USERS (
   USER_NO            INT           NOT NULL AUTO_INCREMENT,
   EMAIL              VARCHAR (100) NOT NULL UNIQUE,
   ARTIST             VARCHAR (45)  NOT NULL,
   NAME               VARCHAR (45)  NOT NULL,
   PW                 VARCHAR (64)  NOT NULL,
   MOBILE             VARCHAR (11)  NOT NULL,
   PROFILE_IMAGE      VARCHAR (500) DEFAULT '/images/basic_profileImage.png',
    GENDER             VARCHAR (2),
   BIRTHYEAR          VARCHAR (4),
   BIRTHDAY           VARCHAR (4),
   POSTCODE           VARCHAR (5),
   ROAD_ADDRESS       VARCHAR (100),
   JIBUN_ADDRESS      VARCHAR (100),
   DETAIL_ADDRESS     VARCHAR (100),
   EXTRA_ADDRESS      VARCHAR (100),
    SNS_TYPE           VARCHAR (10),
    SESSION_ID         VARCHAR (32),
   SESSION_LIMIT_DATE DATETIME,
   JOIN_DATE          DATETIME,
   PW_MODIFY_DATE     DATETIME,
   INFO_MODIFY_DATE   DATETIME,
   AGREE_CODE         INT,
    CONSTRAINT PK_USER PRIMARY KEY(USER_NO)
);

CREATE TABLE SLEEP_USERS (
   USER_NO          INT           NOT NULL,
    EMAIL            VARCHAR (100) NOT NULL,
    ARTIST           VARCHAR (45)  NOT NULL,
    NAME             VARCHAR (45)  NOT NULL,
    PW               VARCHAR (64)  NOT NULL,
    MOBILE           VARCHAR (11)  NOT NULL,
    PROFILE_IMAGE    VARCHAR (500),
    GENDER           VARCHAR (2),
    BIRTHYEAR        VARCHAR (4),
    BIRTHDAY         VARCHAR (4),
    POSTCODE         VARCHAR (5),
    ROAD_ADDRESS     VARCHAR (100),
    JIBUN_ADDRESS    VARCHAR (100),
    DETAIL_ADDRESS   VARCHAR (100),
    EXTRA_ADDRESS    VARCHAR (100),
    SNS_TYPE         VARCHAR (10),
   JOIN_DATE        DATETIME,
   SLEEP_DATE       DATETIME,
    PW_MODIFY_DATE   DATETIME,
    INFO_MODIFY_DATE DATETIME,
    AGREE_CODE       INT,
    CONSTRAINT PK_SLEEP_USERS PRIMARY KEY(USER_NO)
);

CREATE TABLE RETIRE_USERS (
    USER_NO     INT           NOT NULL,
    EMAIL       VARCHAR (100) NOT NULL,
   ARTIST      VARCHAR (45)  NOT NULL,
    RETIRE_DATE DATETIME      NOT NULL,
    CONSTRAINT PK_RETIRE_USERS PRIMARY KEY(USER_NO)
);
-- 회원접속기록 (최근 접속 기록 1개만 유지)
CREATE TABLE ACCESS_LOG (
    ACCESS_LOG_NO INT           NOT NULL AUTO_INCREMENT,
    EMAIL         VARCHAR (100) NOT NULL UNIQUE,
    LOGIN_DATE    DATETIME       NOT NULL,  -- 마지막 로그인일
    CONSTRAINT PK_ACCESS_LOG PRIMARY KEY(ACCESS_LOG_NO),
    CONSTRAINT FK_ACCESS_LOG_USER FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE
);
CREATE TABLE PROFILEIMAGE
(
    PROFILEIMAGE_NO         INT          NOT NULL AUTO_INCREMENT,     -- PK
    PROFILEIMAGE_PATH       VARCHAR (300), -- 파일의 경로
    PROFILEIMAGE_ORIGIN     VARCHAR (300), -- 파일의 원래 이름
    PROFILEIMAGE_FILESYSTEM VARCHAR (42),  -- 파일의 저장된 이름
    EMAIL                   VARCHAR (100), -- 게시글번호, FK
    CONSTRAINT PK_PROFILEIMAGE PRIMARY KEY(PROFILEIMAGE_NO),
    CONSTRAINT FK_PROFILEIMAGE_USER FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE
);


-- 뮤직
CREATE TABLE MUSIC (
    MUSIC_NO          INT             NOT NULL AUTO_INCREMENT,
    EMAIL             VARCHAR (100)   NOT NULL,
    DOWNLOAD_CNT      INT,
    HAS_THUMBNAIL     INT, -- 썸네일이 있으면 1 없으면 0
    MUSIC_TITLE       VARCHAR (100),
    MUSIC_CONTENT     VARCHAR (2000),
    MUSIC_ALBUM       VARCHAR (100),
    MUSIC_GENRE       VARCHAR (30),
    IP                VARCHAR (30),
    IMG_ORIGIN        VARCHAR (300),
    IMG_FILESYSTEM    VARCHAR (40),
    MUSIC_ORIGIN      VARCHAR (300),
    MUSIC_FILESYSTEM  VARCHAR (40),
    IMG_PATH          VARCHAR (300),
    MUSIC_PATH        VARCHAR (300),
    MUSIC_UPLOAD_DATE DATETIME,
    MUSIC_MODIFY_DATE DATETIME,
    CONSTRAINT PK_MUSIC_NO PRIMARY KEY(MUSIC_NO),
    CONSTRAINT FK_MUSIC_NO_USER FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE
);

-- 관리자
CREATE TABLE CHAT_ADMIN (
   CHAT_NO     INT AUTO_INCREMENT NOT NULL, -- 시퀀스
   USER_NO     INT NOT NULL,
   CHAT_DATE   DATETIME,
   IP          VARCHAR(30),
   CONTENT     VARCHAR(100),
   STATE       INT,
   DEPTH       INT,
   GROUP_NO    INT,
   GROUP_ORDER INT,
   CONSTRAINT PK_CHAT_NO PRIMARY KEY(CHAT_NO), -- 기본키(CHAT_NO)
   CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE -- 외래키(USER_NO)
);

-- 관리자 (공지사항, FAQ)
CREATE TABLE BOARD (
    BOARD_NO          INT	NOT NULL	AUTO_INCREMENT,
    BOARD_TITLE       VARCHAR(100),
    BOARD_CONTENT     VARCHAR(4000),
    BOARD_CREATE_DATE DATETIME,
    BOARD_MODIFY_DATE DATETIME,
    BOARD_HIT         INT,
    IP                VARCHAR(30),
    GUBUN             VARCHAR(1),
	CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO) -- 기본키(CHAT_NO)
);
CREATE TABLE UPLOAD (
    UPLOAD_NO	INT		NOT NULL	AUTO_INCREMENT,  -- PK
    TITLE 		VARCHAR(100),   -- 제목
    CONTENT 	VARCHAR(100), -- 내용
    HIT         INT, -- 조회수
    CREATE_DATE DATETIME, -- 작성일
    MODIFY_DATE DATETIME, -- 수정일
	CONSTRAINT PK_UPLOAD_NO PRIMARY KEY(UPLOAD_NO) -- 기본키(CHAT_NO)
);
CREATE TABLE ATTACH (
    ATTACH_NO	  INT		NOT NULL	AUTO_INCREMENT,     -- PK
    PATH 		  VARCHAR(300), 	-- 파일의 경로
    ORIGIN 		  VARCHAR(300), 	-- 파일의 원래 이름
    FILESYSTEM    VARCHAR(42),  	-- 파일의 저장된 이름
    DOWNLOAD_CNT  INT,          	-- 다운로드 횟수
    HAS_THUMBNAIL INT,          	-- 썸네일이 있으면 1, 없으면 0
    UPLOAD_NO 	  INT	NOT NULL,   -- 게시글번호, FK
    CONSTRAINT PK_ATTACH_NO PRIMARY KEY(ATTACH_NO), -- 기본키(CHAT_NO)
    CONSTRAINT FK_ATTACH_UPLOAD FOREIGN KEY(UPLOAD_NO) REFERENCES UPLOAD(UPLOAD_NO) ON DELETE CASCADE -- 외래키(USER_NO)
);
CREATE TABLE SUMMERNOTE_IMAGE (
    BOARD_NO   INT		AUTO_INCREMENT,
    FILESYSTEM VARCHAR(40),
	CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO) -- 기본키(CHAT_NO)
);

CREATE TABLE ACTIVE_LOG
(
	ACTIVE_NO 	INT 			NOT NULL AUTO_INCREMENT,
    EMAIL 		VARCHAR(100) 	NOT NULL,
    MUSIC_NO	INT				NOT NULL,
    LAST_LISTEN_DATE DATETIME,
    LISTEN_COUNT INT,
    CONSTRAINT PK_ACTIVE_LOG PRIMARY KEY(ACTIVE_NO),
	CONSTRAINT FK_ACTIVE_LOG_USERS FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE,
    CONSTRAINT FK_ACTIVE_LOG_MUSIC FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO) ON DELETE CASCADE
    
);


-- PLAYLIST
CREATE TABLE PLAYLIST 
(
	LIST_NO 	INT 			NOT NULL AUTO_INCREMENT,
	EMAIL 		VARCHAR(100) 	NOT NULL,
	LIST_NAME VARCHAR (40),
	CONSTRAINT PK_PLAYLIST PRIMARY KEY(LIST_NO),
    CONSTRAINT FK_PLAYLIST_USERS FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE
    
);

CREATE TABLE MY_MUSIC 
(
	MY_MUSIC_NO INT 			NOT NULL AUTO_INCREMENT,
    LIST_NO		INT,
    MUSIC_NO	INT,
    CONSTRAINT PK_MUSIC PRIMARY KEY(MY_MUSIC_NO),
    CONSTRAINT FK_MY_MUSIC_MUSIC FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO) ON DELETE CASCADE,
    CONSTRAINT FK_MY_MUSIC_PLAYLIST FOREIGN KEY(LIST_NO) REFERENCES PLAYLIST(LIST_NO) ON DELETE CASCADE
);



CREATE TABLE MUSIC_COMMENT
(
	COMMENT_NO	INT				NOT NULL AUTO_INCREMENT,
	MUSIC_NO	INT				NOT NULL,
	EMAIL 		VARCHAR(100) 	NOT NULL,
    COMMENT_CONTENT VARCHAR(1000),
    CREATE_DATE	DATETIME,
    CONSTRAINT PK_MUSIC_COMMENT PRIMARY KEY(COMMENT_NO),
    CONSTRAINT FK_MUSIC_COMMENT_USERS FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE,
    CONSTRAINT FK_MUSIC_COMMENT_MUSIC FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO) ON DELETE CASCADE
    
);


CREATE TABLE MUSIC_LIKE 
(
	LIKE_NO 	INT 			NOT NULL AUTO_INCREMENT,
	EMAIL 		VARCHAR(100) 	NOT NULL,
    MUSIC_NO	INT				NOT NULL,
    CONSTRAINT PK_MUSIC_LIKE PRIMARY KEY(LIKE_NO),
	CONSTRAINT FK_MUSIC_LIKE_USERS FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE,
    CONSTRAINT FK_MUSIC_LIKE_MUSIC FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO) ON DELETE CASCADE
    
);


-- 이용권
CREATE TABLE PASS
(
    PASS_NO     INT 		 NOT NULL AUTO_INCREMENT,
    PASS_NAME   VARCHAR(100) NOT NULL,
    PASS_PRICE  INT      	 NOT NULL,
    CONSTRAINT PK_PASS PRIMARY KEY(PASS_NO)
);
CREATE TABLE PAYMENT
(
    PAY_NO INT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100),
    PASS_NO INT,
    EXPIRATION_DATE DATETIME NOT NULL,
    CONSTRAINT PK_PAYMENT PRIMARY KEY(PAY_NO),
    CONSTRAINT FK_PAYMENT_USERS FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE,
    CONSTRAINT FK_PAYMENT_PASS FOREIGN KEY(PASS_NO) REFERENCES PASS(PASS_NO) ON DELETE CASCADE
);
CREATE TABLE PAYMENT_LOG
(
    PAY_LOG_NO      VARCHAR(30)  NOT NULL,
    PAY_LOG_EMAIL   VARCHAR(100),
    PAY_LOG_NAME    VARCHAR(100),
    PAY_LOG_DATE    DATETIME      NOT NULL,
    PAY_LOG_PG      VARCHAR(100),
    PAY_LOG_PRICE 	INT 		  NOT NULL,
    CONSTRAINT PK_PAYMENT_LOG PRIMARY KEY(PAY_LOG_NO)

);

CREATE TABLE COUPON (
    COUPON_NO INT           NOT NULL AUTO_INCREMENT,
    COUPON_CODE         VARCHAR (20) NOT NULL UNIQUE,
    COUPON_COUNT    INT       NOT NULL,
    COUPON_DATE DATETIME,
    CONSTRAINT PK_COUPON PRIMARY KEY(COUPON_NO)
);
CREATE TABLE COUPON_USE (
    COUPON_USE_NO INT           NOT NULL AUTO_INCREMENT,
    COUPON_CODE         VARCHAR (20) NOT NULL,
    EMAIL    VARCHAR(100)       NOT NULL,
    CONSTRAINT PK_COUPON_USE PRIMARY KEY(COUPON_USE_NO),
    CONSTRAINT FK_COUPON_USE_USER FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE,
    CONSTRAINT FK_COUPON_USE_COUPON FOREIGN KEY(COUPON_CODE) REFERENCES COUPON(COUPON_CODE) ON DELETE CASCADE
    
);
CREATE TABLE ALARM (
    ALARM_NO INT           NOT NULL AUTO_INCREMENT,
    EMAIL    VARCHAR(100)       NOT NULL,
    ALARM_STATUS INT NOT NULL,
    ALARM_CONTENT VARCHAR(500) NOT NULL,
    ALARM_ARRIVAL_TIME DATETIME NOT NULL,
    ALARM_TITLE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_ALARM PRIMARY KEY(ALARM_NO),
    CONSTRAINT FK_ALARM_USER FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL) ON DELETE CASCADE
);


-- 기본 데이터 베이스(관리자 : userNo=1로 고정)
INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('admin@web.com', '관리자', '관리자', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());
INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('grandfa@web.com', '지팡이할아버지', '지팡이', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', DATE_FORMAT('20201010', '%Y%m%d%H%i%s'));

-- 비밀번호 수정 3개월 전 유저
INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE, PW_MODIFY_DATE)
VALUES
    ('password3@web.com', '유통기한3개월', '비밀번호', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', DATE_FORMAT('20220120', '%Y%m%d%H%i%s'), DATE_FORMAT('20220820', '%Y%m%d%H%i%s'));
INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE, PW_MODIFY_DATE)
VALUES
    ('pw3@web.com', '비밀번호3개월', '비번', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', DATE_FORMAT('20220120', '%Y%m%d%H%i%s'), DATE_FORMAT('20220820', '%Y%m%d%H%i%s'));


-- 11개월 전 접속 유저
INSERT INTO USERS (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES ('unlog11@web.com', '11개월전접속', '곰팡이', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', DATE_FORMAT('20220120', '%Y%m%d%H%i%s'));
-- 11개월 전 접속 로그
INSERT INTO ACCESS_LOG (EMAIL, LOGIN_DATE)
VALUES ('unlog11@web.com', DATE_FORMAT('20220120', '%Y%m%d%H%i%s'));

INSERT INTO USERS (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE) VALUES ('practice@web.com', '연습1', '연습1', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', '2022-12-12 12:12:12');
INSERT INTO USERS (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE) VALUES ('music1@web.com', '음악테스트계정', '김김김', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', '2022-12-12 12:12:12');


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user1@web.com', '유자차좋아해요', '김유자', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user2@web.com', '카페인중독자', '정커피', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user3@web.com', '코로나아님', '엄코로', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user4@web.com', '물티슈', '황티슈', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user5@web.com', '황치즈베이글', '조황티', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user6@web.com', '여름이온다', '구예인', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user7@web.com', '봄이좋냐?', '장범준', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user8@web.com', '코로롱걸리고후각읽음', '조한나', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user9@web.com', '짱테이시', '황규은', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user10@web.com', '베트남한국 반반인간', '우혼혈', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user11@web.com', '니혼진', '다나카', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());

INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user12@web.com', '구디인', '엄동규', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user13@web.com', '홍길동이라고읽고홍길동이라고씁니다', '홍길동', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    ('user14@web.com', '메가스터디', '조재수', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', NOW());


INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('abc111@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '거북이와두루미', '김종수', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
    
    
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('o2of782@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '코딩하는 사람', '김수형', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
        
        
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('qirfasdfi@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '할리스에있는사람', '김할리', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
       
       
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('dondaond44@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '노란색옷입은사람', '김나영', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
       
       
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('dondd44@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '빨간색 옷 입은 사람', '김대박', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
        
        
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('dondfage7852@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '크리스마스에솔로인사람', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
        
        
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('eifdaq1231322@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '솔로가진짜인사람', '김모임', 'No', '01099668578', null, null, null, null, null, null, null, 4, null, NOW(), null, null, null, null);
        
        
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('ei54efd22@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'Ditto', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
                                    
	
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('banban@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'Deetoo', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
                                    
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('newnewban@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'Banheesu', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 2, null, NOW(), null, null, null, null);
          
                                    
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('aespa156489@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '카리나팬인사람', '임플랜', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
             
                                    
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('aes4156pa159@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '겨울하면윈터지', '임겨울', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
 
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('aedfae7pa159@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '굶주린사자', '강고양', 'F', '01099668578', null, null, null, null, null, null, null, 1, null, NOW(), null, null, null, null);
   
     
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('omorw722@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '에어팟 한 쪽 없는 사람', '송소내', 'F', '01084498578', null, null, null, null, null, null, null, 2, null, NOW(), null, null, null, null);
              
              
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('o752322@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '에어팟 두 쪽 있는 사람', '엄희라', 'F', '01084498578', null, null, null, null, null, null, null, 4, null, NOW(), null, null, null, null);
     
              
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('eeodsp45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '스파이일 수도 있는 사람', '김무비', 'F', '01089675578', null, null, null, null, null, null, null, 3, null, NOW(), null, null, null, null);
	
              
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('eeo781p45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '뉴진스 여섯번째 멤버', '이혜원', 'F', '01085745578', null, null, null, null, null, null, null, 1, null, NOW(), null, null, null, null);
     

INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('852qwd45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '뉴진스새멤버', '김민지', 'F', '01075145578', null, null, null, null, null, null, null, 3, null, NOW(), null, null, null, null);
     
     
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('aa852qwd45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'new진수', '반희수', 'F', '01075141254', null, null, null, null, null, null, null, 2, null, NOW(), null, null, null, null);
     
     
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('asdxczd45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '뉴jeans스', '반희수', 'F', '01075141254', null, null, null, null, null, null, null, 3, null, NOW(), null, null, null, null);


INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('asfvarv8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'sayit디도', '이해린', 'F', '01075141254', null, null, null, null, null, null, null, 2, null, NOW(), null, null, null, null);
     
     
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('748v8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'sayitback', '김바란', 'F', '0107557954', null, null, null, null, null, null, null, 1, null, NOW(), null, null, null, null);
     

INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('785qsdv8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '고오고오고', '김고오', 'F', '0107557954', null, null, null, null, null, null, null, 3, null, NOW(), null, null, null, null);
     
	
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('7qdsadjdv8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '디도말해', '반희수', 'F', '0107557954', null, null, null, null, null, null, null, 1, null, NOW(), null, null, null, null);
     
     
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('whatwhat1@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '아이즈원시퀀스', '장원영', 'F', '0107557954', null, null, null, null, null, null, null, 2, null, NOW(), null, null, null, null);
     
     
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('whay1@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '문을열어봐', '장원영', 'F', '0107557954', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
    
    
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('ekfasdf7521@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '댓어시퀀스', '김채원', 'F', '0107557954', null, null, null, null, null, null, null, 3, null, NOW(), null, null, null, null);
    
    
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('ge5df7521@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '조용하지마!', '유나', 'F', '0107557954', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);


INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('g857521@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '강혜원입니다', '강혜원', 'F', '0107557954', null, null, null, null, null, null, null, 2, null, NOW(), null, null, null, null);
   
   
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('smail21@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '항상웃자!', '최예나', 'F', '01095244832', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
   
   
INSERT INTO USERS
    (EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    ('panorama@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '이건..운명', '야부키', 'F', '01095244832', null, null, null, null, null, null, null, 0, null, NOW(), null, null, null, null);
 
 



-- CHAT_ADMIN 기초 데이터

INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (18, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 18, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (18, NOW() ,'0:0:0:0:0:0:0:1', '안녕하세요', 1, 1, 18, 5);  
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (18, NOW() ,'0:0:0:0:0:0:0:1', '어제 데뷔한', 1, 1, 18, 4);  
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (18, NOW() ,'0:0:0:0:0:0:0:1', '신입입니다', 1, 1, 18, 3); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (18, NOW() ,'0:0:0:0:0:0:0:1', '잘 부탁드립니다!', 1, 1, 18, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (18, NOW() ,'0:0:0:0:0:0:0:1', ':D', 1, 1, 18, 1);    
    

INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (19, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 19, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (19, NOW() ,'0:0:0:0:0:0:0:1', '태그뮤직 예쁘네요', 1, 1, 19, 3); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (19, NOW() ,'0:0:0:0:0:0:0:1', '아주 멋져요', 1, 1, 19, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (19, NOW() ,'0:0:0:0:0:0:0:1', '갖고 싶어요 ㅎㅎ', 1, 1, 19, 1); 
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (2, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 1, 0);
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (2, NOW() ,'0:0:0:0:0:0:0:1', '문의드립니다.', 1, 1, 1, 3);    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (2, NOW() ,'0:0:0:0:0:0:0:1', '닉네임은 어떻게 변경하나요.', 1, 1, 1, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (2, NOW() ,'0:0:0:0:0:0:0:1', '빨리 답장해주세요.', 1, 1, 1, 1); 
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (3, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 3, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (3, NOW() ,'0:0:0:0:0:0:0:1', '안녕하세요~', 1, 1, 3, 2);  
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (3, NOW() ,'0:0:0:0:0:0:0:1', '이용권 결제는 어떻게 하나요?', 1, 1, 3, 1);    
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (4, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 4, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (4, NOW() ,'0:0:0:0:0:0:0:1', '닉넴 변경은 어케하나요?', 1, 1, 4, 1);        
        

INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (5, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 5, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (5, NOW() ,'0:0:0:0:0:0:0:1', '관리자님', 1, 1, 5, 5);  
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (5, NOW() ,'0:0:0:0:0:0:0:1', '곡을 올렸는데', 1, 1, 5, 4);  
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (5, NOW() ,'0:0:0:0:0:0:0:1', '리스트에 제 곡이 안보여요', 1, 1, 5, 3); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (5, NOW(),'0:0:0:0:0:0:0:1', '흠', 1, 1, 5, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (5, NOW(),'0:0:0:0:0:0:0:1', '다시 찾아볼게요', 1, 1, 5, 1); 


INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (6, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 6, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (6, NOW() ,'0:0:0:0:0:0:0:1', '제가 할 말이 있습니다', 1, 1, 6, 3); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (6, NOW() ,'0:0:0:0:0:0:0:1', '저 성공하고 싶어요', 1, 1, 6, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (6, NOW() ,'0:0:0:0:0:0:0:1', '도와주세요', 1, 1, 6, 1); 


INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 7, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '헬로', 1, 1, 7, 7); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '마임네임', 1, 1, 7, 6); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '이즈', 1, 1, 7, 5); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '김나영데스', 1, 1, 7, 4); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '나이스트미츄', 1, 1, 7, 3); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '아이원트', 1, 1, 7, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (7, NOW() ,'0:0:0:0:0:0:0:1', '음악업로드. 오케이?', 1, 1, 7, 1); 


INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (8, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 8, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (8, NOW() ,'0:0:0:0:0:0:0:1', '관리자양반', 1, 1, 8, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (8, NOW() ,'0:0:0:0:0:0:0:1', '음악업로드 어떻게 하는 것이오?', 1, 1, 8, 1); 


INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (9, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 9, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (9, NOW() ,'0:0:0:0:0:0:0:1', '뭐지', 1, 1, 9, 2);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (9, NOW() ,'0:0:0:0:0:0:0:1', '이용권 결제가 두 번 됐는데요?', 1, 1, 9, 1);
    

INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (10, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 10, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (10, NOW() ,'0:0:0:0:0:0:0:1', '헤이~~', 1, 1, 10, 1);    
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (11, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 11, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (11, NOW() ,'0:0:0:0:0:0:0:1', '오~~~~~~', 1, 1, 11, 1);      
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (12, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 12, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (12, NOW() ,'0:0:0:0:0:0:0:1', 'hello', 1, 1, 12, 1);       
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (13, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 13, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (13, NOW() ,'0:0:0:0:0:0:0:1', '니하오', 1, 1, 13, 1);     
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (14, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 14, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (14, NOW() ,'0:0:0:0:0:0:0:1', '아배고파', 1, 1, 14, 1);     
    

INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (15, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 15, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (15, NOW() ,'0:0:0:0:0:0:0:1', '저 곡 올렸어요', 1, 1, 15, 1);     


INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (21, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 21, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (21, NOW() ,'0:0:0:0:0:0:0:1', '팔을 좀 더 길게 뻗어도 ', 1, 1, 21, 2); 
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (21, NOW() ,'0:0:0:0:0:0:0:1', '뒷꿈치 어쩌고 ', 1, 1, 21, 1);     
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (22, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 22, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (22, NOW() ,'0:0:0:0:0:0:0:1', 'You keep me wrapped around your finger', 1, 1, 22, 2);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (22, NOW() ,'0:0:0:0:0:0:0:1', 'Wrapped around your finger', 1, 1, 22, 1);   
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (23, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 23, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (23, NOW() ,'0:0:0:0:0:0:0:1', 'Why do I tell myself that I will do the best I can?', 1, 1, 23, 1); 

    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (24, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 15, 0);    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (24, NOW() ,'0:0:0:0:0:0:0:1', 'Then was shot back down to Earth', 1, 1, 15, 1);   
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (25, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 25, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (25, NOW() ,'0:0:0:0:0:0:0:1', 'Ooh, covered in carats', 1, 1, 25, 2);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (25, NOW() ,'0:0:0:0:0:0:0:1', 'Ooh, but then you just vanished', 1, 1, 25, 1);   
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (27, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 27, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (27, NOW() ,'0:0:0:0:0:0:0:1', 'Got a hundred big faces, but I am still alone', 1, 1, 27, 2);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (27, NOW() ,'0:0:0:0:0:0:0:1', 'Ayy, I would throw it all away', 1, 1, 27, 1);     
    
    
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (29, NOW() ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 29, 0);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (29, NOW() ,'0:0:0:0:0:0:0:1', 'I would throw it all away', 1, 1, 29, 2);
INSERT INTO CHAT_ADMIN
    (USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (29, NOW() ,'0:0:0:0:0:0:0:1', 'I just keep on wishin that the money made you stay', 1, 1, 29, 1);      




-- 음악 게시물 기초 데이터

-- 음악 게시물 기초 데이터
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('practice@web.com', '관리제목1', '내용1', '앨범1' , '락', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('practice@web.com', '관리제목2', '내용1', '앨범2' , '팝송', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목3', '내용1', '앨범3' , '발라드', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목4', '내용1', '앨범4' , '클래식', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('practice@web.com', '관리제목5', '내용1', '앨범5' , '락', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목6', '내용1', '앨범1' , '팝송', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목7', '내용1', '앨범2' , '발라드', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', '', '음악1', 'DB음악1', 0, '', 'storage\\\\2022\\\\12\\\\23', 0);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목8', '내용1', '앨범3' , '팝송', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목9', '내용1', '앨범4' , '클래식', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목10', '내용1', '앨범5' , '팝송', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('practice@web.com', '관리제목11', '내용1', '앨범1' , '트로트', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목12', '내용1', '앨범2' , '클래식', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('practice@web.com', '관리제목13', '내용1', '앨범3' , '트로트', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목14', '내용1', '앨범4' , '발라드', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목15', '내용1', '앨범5' , '락', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', '', '음악1', 'DB음악1', 0, '', 'storage\\\\2022\\\\12\\\\23', 0);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목16', '내용1', '앨범1' , '트로트', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목17', '내용1', '앨범2' , '발라드', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', '', '음악1', 'DB음악1', 0, '', 'storage\\\\2022\\\\12\\\\23', 0);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목18', '내용1', '앨범3' , '트로트', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목19', '내용1', '앨범4' , '발라드', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', '', '음악1', 'DB음악1', 0, '', 'storage\\\\2022\\\\12\\\\23', 0);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목20', '내용1', '앨범5' , '클래식', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목21', '내용1', '앨범5' , '클래식', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);
INSERT INTO MUSIC (EMAIL, MUSIC_TITLE, MUSIC_CONTENT, MUSIC_ALBUM, MUSIC_GENRE, MUSIC_UPLOAD_DATE, MUSIC_MODIFY_DATE, IP, IMG_ORIGIN, IMG_FILESYSTEM, MUSIC_ORIGIN, MUSIC_FILESYSTEM, DOWNLOAD_CNT, IMG_PATH, MUSIC_PATH, HAS_THUMBNAIL )
VALUES 
('admin@web.com', '관리제목22', '내용1', '앨범5' , '클래식', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '00000001', '이미지1', 'animal1.jpg', '음악1', 'DB음악1', 0, 'storage\\\\2022\\\\12\\\\23', 'storage\\\\2022\\\\12\\\\23', 1);


-- 로그 기초데이터 : USER 테이블의 EMAIL과  MUSIC 테이블의 MUSIC_NO를 복수의 FK로 받는다
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('practice@web.com', '1', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('practice@web.com', '2', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '3', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '4', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('practice@web.com', '5', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '6', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '7', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '8', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '9', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '10', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('practice@web.com', '11', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '12', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('practice@web.com', '13', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '14', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '15', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '16', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '17', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '18', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '19', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '20', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '21', '2022-12-12 12:12:12', 0);
INSERT INTO ACTIVE_LOG (EMAIL, MUSIC_NO, LAST_LISTEN_DATE, LISTEN_COUNT ) VALUES ('admin@web.com', '22', '2022-12-12 12:12:12', 0);

-- 좋아요 수 기초데이터
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 1);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 2);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('practice@web.com', 11);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 4);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('practice@web.com', 15);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 9);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('practice@web.com', 15);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 8);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('practice@web.com', 11);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('practice@web.com', 7);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 19);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 19);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 19);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 3);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('admin@web.com', 3);
INSERT INTO MUSIC_LIKE (EMAIL, MUSIC_NO) VALUES ('music1@web.com', 3);

-- 댓글수 기초데이터
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (3, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (3, 'practice@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (3, 'practice@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (4, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (5, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (7, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (8, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (13, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (13, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (2, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (2, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (1, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (2, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (7, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');
INSERT INTO MUSIC_COMMENT (MUSIC_NO, EMAIL, COMMENT_CONTENT, CREATE_DATE) VALUES (8, 'admin@web.com', '댓글1', '2022-12-12 12:12:12');

-- 플레이리스트 기초데이터   
INSERT INTO PLAYLIST(EMAIL, LIST_NAME) VALUES ('music1@web.com', '연습용리스트1');
INSERT INTO PLAYLIST(EMAIL, LIST_NAME) VALUES ('music1@web.com', '연습용리스트2');


UPDATE PLAYLIST SET LIST_NAME = '알랑알랑' WHERE LIST_NO = 1 AND EMAIL = 'music1@web.com';
   

-- 플레이리스트에 담긴 음악 기초데이터
INSERT INTO MY_MUSIC(LIST_NO, MUSIC_NO) VALUES (1, '1');
INSERT INTO MY_MUSIC(LIST_NO, MUSIC_NO) VALUES (1, '2');
INSERT INTO MY_MUSIC(LIST_NO, MUSIC_NO) VALUES (1, '3');
INSERT INTO MY_MUSIC(LIST_NO, MUSIC_NO) VALUES (2, '7');
INSERT INTO MY_MUSIC(LIST_NO, MUSIC_NO) VALUES (2, '9');

-- 음악 좋아요 기초데이터





    
INSERT INTO PASS
    (PASS_NAME, PASS_PRICE)
VALUES 
    ('30일이용권', 100);
INSERT INTO PASS
    (PASS_NAME, PASS_PRICE)
VALUES 
    ('정액이용권', 80);
    
INSERT INTO COUPON
	(COUPON_CODE, COUPON_COUNT, COUPON_DATE)
 VALUES
	('AA12BB34CC56DD78', 500, DATE_ADD(NOW(), INTERVAL 1 YEAR));


COMMIT;