-- 시퀀스 삭제
DROP SEQUENCE MUSIC_LIKE_SEQ;
DROP SEQUENCE MUSIC_COMMENT_SEQ;
DROP SEQUENCE PLAYLIST_SEQ;
DROP SEQUENCE MY_MUSIC_SEQ;
DROP SEQUENCE ACTIVE_LOG_SEQ;
DROP SEQUENCE MUSIC_SEQ;
DROP SEQUENCE CHAT_SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE PAYMENT_SEQ;
DROP SEQUENCE PAYMENT_LOG_SEQ;
DROP SEQUENCE PASS_SEQ;
DROP SEQUENCE USERS_SEQ;


-- 시퀀스 생성
CREATE SEQUENCE USERS_SEQ NOCACHE;
CREATE SEQUENCE PAYMENT_LOG_SEQ NOCACHE;
CREATE SEQUENCE PAYMENT_SEQ NOCACHE;
CREATE SEQUENCE PASS_SEQ NOCACHE;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
CREATE SEQUENCE CHAT_SEQ NOCACHE;
CREATE SEQUENCE MUSIC_SEQ NOCACHE;
CREATE SEQUENCE ACTIVE_LOG_SEQ NOCACHE;
CREATE SEQUENCE MY_MUSIC_SEQ NOCACHE;
CREATE SEQUENCE PLAYLIST_SEQ NOCACHE;
CREATE SEQUENCE MUSIC_COMMENT_SEQ NOCACHE;
CREATE SEQUENCE MUSIC_LIKE_SEQ NOCACHE;

-- 테이블 삭제
DROP TABLE ACTIVE_LOG    CASCADE CONSTRAINTS;
DROP TABLE MY_MUSIC      CASCADE CONSTRAINTS;
DROP TABLE PLAYLIST      CASCADE CONSTRAINTS;
DROP TABLE MUSIC_COMMENT CASCADE CONSTRAINTS;
DROP TABLE MUSIC_LIKE    CASCADE CONSTRAINTS;
DROP TABLE MUSIC         CASCADE CONSTRAINTS;
DROP TABLE CHAT_ADMIN;
DROP TABLE BOARD;
DROP TABLE PAYMENT;
DROP TABLE PAYMENT_LOG;
DROP TABLE PASS;
DROP TABLE RETIRE_USERS;
DROP TABLE SLEEP_USERS;
DROP TABLE USERS;

-- 테이블 생성
CREATE TABLE USERS (
	USER_NO	           NUMBER	            NOT NULL,
	EMAIL	           VARCHAR2 (100 BYTE)   NOT NULL,
	ARTIST	           VARCHAR2 (45 BYTE)   NOT NULL,
	NAME	           VARCHAR2 (45 BYTE)   NOT NULL,
	PW	               VARCHAR2 (64 BYTE)   NOT NULL,
    PROFILE_IMAGE      VARCHAR2 (500 BYTE),
	MOBILE	           VARCHAR2 (11 BYTE)   NOT NULL,
    GENDER	           VARCHAR2 (2 BYTE),
	BIRTHYEAR	       VARCHAR2 (4 BYTE),
	BIRTHDAY	       VARCHAR2 (4 BYTE),
	POSTCODE	       VARCHAR2 (5 BYTE),
	ROAD_ADDRESS	   VARCHAR2 (100 BYTE),
	JIBUN_ADDRESS	   VARCHAR2 (100 BYTE),
	DETAIL_ADDRESS	   VARCHAR2 (100 BYTE),
	EXTRA_ADDRESS	   VARCHAR2 (100 BYTE),
    SNS_TYPE	       VARCHAR2 (10 BYTE),
    SESSION_ID         VARCHAR2 (32 BYTE),
	SESSION_LIMIT_DATE DATE,
	JOIN_DATE	       DATE,
	PW_MODIFY_DATE     DATE,
	INFO_MODIFY_DATE   DATE,
	AGREE_CODE	       NUMBER
);

CREATE TABLE SLEEP_USERS (
	USER_NO	          NUMBER	            NOT NULL,
	EMAIL	          VARCHAR2 (100 BYTE)	NOT NULL,
	ARTIST	          VARCHAR2 (45 BYTE)	NOT NULL,
	NAME	          VARCHAR2 (45 BYTE)	NOT NULL,
	PW	              VARCHAR2 (64 BYTE)	NOT NULL,
    MOBILE	          VARCHAR2 (11 BYTE)    NOT NULL,
    JOIN_DATE	      DATE	                NOT NULL,
    SLEEP_DATE	      DATE                  NOT NULL,
    PROFILE_IMAGE	  VARCHAR2 (500 BYTE) ,
	GENDER	          VARCHAR2 (2 BYTE),
	BIRTHYEAR	      VARCHAR2 (4 BYTE),
	BIRTHDAY	      VARCHAR2 (4 BYTE),
	POSTCODE	      VARCHAR2 (5 BYTE),
	ROAD_ADDRESS	  VARCHAR2 (100 BYTE),
	JIBUN_ADDRESS	  VARCHAR2 (100 BYTE),
	DETAIL_ADDRESS    VARCHAR2 (100 BYTE),
	EXTRA_ADDRESS	  VARCHAR2 (100 BYTE),
	AGREE_CODE	      NUMBER,
	SNS_TYPE	      VARCHAR2 (10 BYTE),
	PW_MODIFY_DATE	  DATE,
	INFO_MODIFY_DATE  DATE
);

CREATE TABLE RETIRE_USERS (
	USER_NO 	NUMBER	           NOT NULL,
	EMAIL	    VARCHAR2 (100 BYTE) NOT NULL,
	RETIRE_DATE	DATE               NOT NULL,
	ARTIST	    VARCHAR2 (45 BYTE) NOT NULL
);

CREATE TABLE PASS(
    PASS_NO     NUMBER      NOT NULL,
    PASS_NAME   VARCHAR2(100 BYTE)      NOT NULL,
    PASS_PRICE  NUMBER      NOT NULL
);
CREATE TABLE PAYMENT(
    PAY_NO NUMBER NOT NULL,
    EMAIL VARCHAR2(100 BYTE),
    PASS_NO NUMBER,
    PAY_DATE DATE NOT NULL
);
CREATE TABLE PAYMENT_LOG(
    PAY_LOG_NO      NUMBER      NOT NULL,
    PAY_LOG_EMAIL       VARCHAR2(100 BYTE),
    PASS_NO     NUMBER,
    PAY_LOG_DATE    DATE        NOT NULL,
    PAY_LOG_PG      VARCHAR2(100 BYTE)

);

CREATE TABLE BOARD (
	BOARD_NO          NUMBER                NOT NULL,
	BOARD_TITLE       VARCHAR2(100  BYTE),
	BOARD_CONTENT	  VARCHAR2(4000 BYTE),
	BOARD_CREATE_DATE DATE,
	BOARD_HIT         NUMBER,
	IP	              VARCHAR2(30 BYTE),
	GUBUN	          VARCHAR2(1 BYTE)
);

CREATE TABLE CHAT_ADMIN (
   CHAT_NO     NUMBER             NOT NULL,
   USER_NO     NUMBER             NOT NULL,
   CHAT_DATE   DATE,
   IP          VARCHAR2(30 BYTE),
   CONTENT     VARCHAR2(100 BYTE),
   STATE       NUMBER(1),
   DEPTH       NUMBER(2),
   GROUP_NO    NUMBER,
   GROUP_ORDER NUMBER
);

CREATE TABLE MUSIC (
    MUSIC_NO          NUMBER	           NOT NULL,
    EMAIL	          VARCHAR2 (45 BYTE)   NOT NULL,
	MUSIC_TITLE	      VARCHAR2 (100 BYTE),
	MUSIC_CONTENT	  VARCHAR2 (2000 BYTE),
	MUSIC_ALBUM	      VARCHAR2 (100 BYTE),
	MUSIC_GENRE	      VARCHAR2 (30 BYTE),
	MUSIC_UPLOAD_DATE DATE,
	MUSIC_MODIFY_DATE DATE,
	IP                VARCHAR2 (30 BYTE),
	IMG_ORIGIN	      VARCHAR2 (300 BYTE),
	IMG_FILESYSTEM	  VARCHAR2 (40 BYTE),
	MUSIC_ORIGIN	  VARCHAR2 (300 BYTE),
	MUSIC_FILESYSTEM  VARCHAR2 (40 BYTE),
	DOWNLOAD_CNT	  NUMBER,
	IMG_PATH	      VARCHAR2 (300 BYTE),
	MUSIC_PATH	      VARCHAR2 (300 BYTE),
    HAS_THUMBNAIL   NUMBER
    -- 썸네일이 있으면 1 없으면 0
);

CREATE TABLE ACTIVE_LOG (
    ACTIVE_NO	     NUMBER	            NOT NULL,
	EMAIL	         VARCHAR2 (100 BYTE)	NOT NULL,
	MUSIC_NO	     NUMBER	            NOT NULL,
	LAST_LISTEN_DATE DATE,
	LISTEN_COUNT     NUMBER
);

CREATE TABLE MY_MUSIC (
    MY_MUSIC_NO NUMBER NOT NULL,
	LIST_NO     NUMBER NOT NULL,
	MUSIC_NO    NUMBER NOT NULL
);

CREATE TABLE PLAYLIST (
    LIST_NO    NUMBER	          NOT NULL,
	EMAIL      VARCHAR2 (100 BYTE) NOT NULL,
	GROUP_NAME VARCHAR2 (40 BYTE)
);

CREATE TABLE MUSIC_COMMENT (
    COMMENT_NO	    NUMBER	              NOT NULL,
    MUSIC_NO	    NUMBER	              NOT NULL,
	EMAIL	        VARCHAR2 (100 BYTE)    NOT NULL,
	COMMENT_CONTENT VARCHAR2 (1000 BYTE),
	CREATE_DATE	    DATE
);

CREATE TABLE MUSIC_LIKE (
    LIKE_NO	 NUMBER	            NOT NULL,
	EMAIL	 VARCHAR2 (100 BYTE)	NOT NULL,
	MUSIC_NO NUMBER	            NOT NULL
);


-- 관계키 형성
-- 기본키
ALTER TABLE USERS
    ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_NO);
ALTER TABLE SLEEP_USERS
    ADD CONSTRAINT PK_SLEEP_USERS PRIMARY KEY (USER_NO);
ALTER TABLE RETIRE_USERS
    ADD CONSTRAINT PK_RETIRE_USERS PRIMARY KEY (USER_NO);
ALTER TABLE PASS
    ADD CONSTRAINT PK_PASS PRIMARY KEY (PASS_NO);
ALTER TABLE PAYMENT_LOG
    ADD CONSTRAINT PK_PAYMENT_LOG PRIMARY KEY (PAY_LOG_NO);
ALTER TABLE PAYMENT
    ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (PAY_NO);
ALTER TABLE BOARD
    ADD CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NO);
ALTER TABLE CHAT_ADMIN
    ADD CONSTRAINT PK_CHAT_ADMIN PRIMARY KEY (CHAT_NO);
ALTER TABLE MUSIC
    ADD CONSTRAINT PK_MUSIC PRIMARY KEY (MUSIC_NO);
ALTER TABLE ACTIVE_LOG
    ADD CONSTRAINT PK_ACTIVE_LOG PRIMARY KEY (ACTIVE_NO);
ALTER TABLE PLAYLIST
    ADD CONSTRAINT PK_PLAYLIST PRIMARY KEY (LIST_NO);
ALTER TABLE MY_MUSIC
    ADD CONSTRAINT PK_MY_MUSIC PRIMARY KEY (MY_MUSIC_NO);
ALTER TABLE MUSIC_COMMENT
    ADD CONSTRAINT PK_MUSIC_COMMENTE PRIMARY KEY (COMMENT_NO);
ALTER TABLE MUSIC_LIKE
    ADD CONSTRAINT PK_MUSIC_LIKE PRIMARY KEY (LIKE_NO);


-- 고유키 : USERS
ALTER TABLE USERS
    ADD CONSTRAINT UK_USERS UNIQUE (EMAIL);

-- 외래키 : CHAT_ADMIN 테이블
ALTER TABLE CHAT_ADMIN
    ADD CONSTRAINT FK_CHAT_ADMIN_USERS
        FOREIGN KEY (USER_NO) REFERENCES USERS (USER_NO)
            ON DELETE CASCADE;
-- 외래키 : ACTIVE_LOG 테이블
ALTER TABLE ACTIVE_LOG
    ADD CONSTRAINT FK_ACTIVE_LOG_USERS
        FOREIGN KEY (EMAIL) REFERENCES USERS (EMAIL)
            ON DELETE CASCADE;
ALTER TABLE ACTIVE_LOG
    ADD CONSTRAINT FK_ACTIVE_LOG_MUSIC
        FOREIGN KEY (MUSIC_NO) REFERENCES MUSIC (MUSIC_NO)
            ON DELETE CASCADE;
-- 외래키 : PLAYLIST 테이블
ALTER TABLE PLAYLIST
    ADD CONSTRAINT FK_PLAYLIST_USERS
        FOREIGN KEY(EMAIL) REFERENCES USERS (EMAIL)
            ON DELETE CASCADE;
-- 외래키 : MY_MUSIC 테이블
ALTER TABLE MY_MUSIC
    ADD CONSTRAINT FK_MY_MUSIC_MUSIC
        FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO)
            ON DELETE CASCADE;
-- 외래키 : MUSIC_COMMENT
ALTER TABLE MUSIC_COMMENT
    ADD CONSTRAINT FK_MUSIC_COMMENT_USERS
        FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
            ON DELETE CASCADE;
ALTER TABLE MUSIC_COMMENT
    ADD CONSTRAINT FK_MUSIC_COMMENT_MUSIC
        FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO)
            ON DELETE CASCADE;
-- 외래키 : MUSIC_LIKE
ALTER TABLE MUSIC_LIKE
    ADD CONSTRAINT FK_MUSIC_LIKE_USERS
        FOREIGN KEY(EMAIL) REFERENCES USERS(EMAIL)
            ON DELETE CASCADE;
ALTER TABLE MUSIC_LIKE
    ADD CONSTRAINT FK_MUSIC_LIKE_MUSIC
        FOREIGN KEY(MUSIC_NO) REFERENCES MUSIC(MUSIC_NO)
            ON DELETE CASCADE;
ALTER TABLE PAYMENT
    ADD CONSTRAINT FK_PAYMENT_USERS
        FOREIGN KEY (EMAIL) REFERENCES USERS (EMAIL)
            ON DELETE CASCADE;            
ALTER TABLE PAYMENT
    ADD CONSTRAINT FK_PAYMENT_PASS
        FOREIGN KEY(PASS_NO)REFERENCES PASS(PASS_NO)
            ON DELETE CASCADE;
-- 디폴트
ALTER TABLE USERS
    MODIFY PROFILE_IMAGE
        DEFAULT '/images/basic_profileImage.png';

-- 기본 데이터 베이스(관리자 : userNo=1로 고정)
INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'admin@web.com', '관리자', '관리자', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

-- 기본 데이터 베이스(유저)
INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user1@web.com', '회원1', '회원본명1', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user2@web.com', '회원2', '회원본명2', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user3@web.com', '회원3', '회원본명3', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user4@web.com', '회원4', '회원본명4', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user5@web.com', '회원5', '회원본명5', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user6@web.com', '회원6', '회원본명6', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user7@web.com', '회원7', '회원본명7', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);


INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user8@web.com', '회원8', '회원본명8', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);


INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user9@web.com', '회원9', '회원본명9', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user10@web.com', '회원10', '회원본명10', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);


INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user11@web.com', '회원11', '회원본명11', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user12@web.com', '회원12', '회원본명12', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);


INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user13@web.com', '회원13', '회원본명13', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);

INSERT INTO USERS
    (USER_NO, EMAIL, ARTIST, NAME, PW, MOBILE, JOIN_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'user14@web.com', '회원14', '회원본명14', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '01011111111', SYSDATE);




-- 기본데이터 베이스 (1:1 문의)
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 2, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 1, 0);
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 2, SYSDATE ,'0:0:0:0:0:0:0:1', '문의드립니다.', 1, 1, 1, 3);    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 2, SYSDATE ,'0:0:0:0:0:0:0:1', '닉네임은 어떻게 변경하나요.', 1, 1, 1, 2); 

INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 2, SYSDATE ,'0:0:0:0:0:0:0:1', '빨리 답장해주세요.', 1, 1, 1, 1); 
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 3, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 3, 0);    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 3, SYSDATE ,'0:0:0:0:0:0:0:1', '안녕하세요~', 1, 1, 3, 2);  
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 3, SYSDATE ,'0:0:0:0:0:0:0:1', '이용권 결제는 어떻게 하나요?', 1, 1, 3, 1);    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 4, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 4, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 4, SYSDATE ,'0:0:0:0:0:0:0:1', '닉넴 변경은 어케하나요?', 1, 1, 4, 1);        
        

INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 5, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 5, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 5, SYSDATE ,'0:0:0:0:0:0:0:1', '관리자님', 1, 1, 5, 5);  
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 5, SYSDATE ,'0:0:0:0:0:0:0:1', '곡을 올렸는데', 1, 1, 5, 4);  
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 5, SYSDATE ,'0:0:0:0:0:0:0:1', '리스트에 제 곡이 안보여요', 1, 1, 5, 3); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 5, SYSDATE ,'0:0:0:0:0:0:0:1', '흠', 1, 1, 5, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 5, SYSDATE ,'0:0:0:0:0:0:0:1', '다시 찾아볼게요', 1, 1, 5, 1); 


INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 6, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 6, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 6, SYSDATE ,'0:0:0:0:0:0:0:1', '제가 할 말이 있습니다', 1, 1, 6, 3); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 6, SYSDATE ,'0:0:0:0:0:0:0:1', '저 성공하고 싶어요', 1, 1, 6, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 6, SYSDATE ,'0:0:0:0:0:0:0:1', '도와주세요', 1, 1, 6, 1); 


INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 7, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '헬로', 1, 1, 7, 7); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '마임네임', 1, 1, 7, 6); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '이즈', 1, 1, 7, 5); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '김나영데스', 1, 1, 7, 4); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '나이스트미츄', 1, 1, 7, 3); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '아이원트', 1, 1, 7, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 7, SYSDATE ,'0:0:0:0:0:0:0:1', '음악업로드. 오케이?', 1, 1, 7, 1); 


INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 8, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 8, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 8, SYSDATE ,'0:0:0:0:0:0:0:1', '관리자양반', 1, 1, 8, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 8, SYSDATE ,'0:0:0:0:0:0:0:1', '음악업로드 어떻게 하는 것이오?', 1, 1, 8, 1); 


INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 9, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 9, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 9, SYSDATE ,'0:0:0:0:0:0:0:1', '뭐지', 1, 1, 9, 2);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 9, SYSDATE ,'0:0:0:0:0:0:0:1', '이용권 결제가 두 번 됐는데요?', 1, 1, 9, 1);
    


INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 10, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 10, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 10, SYSDATE ,'0:0:0:0:0:0:0:1', '헤이~~', 1, 1, 10, 1);    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 11, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 11, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 11, SYSDATE ,'0:0:0:0:0:0:0:1', '오~~~~~~', 1, 1, 11, 1);      
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 12, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 12, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 12, SYSDATE ,'0:0:0:0:0:0:0:1', 'hello', 1, 1, 12, 1);       
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 13, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 13, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 13, SYSDATE ,'0:0:0:0:0:0:0:1', '니하오', 1, 1, 13, 1);     
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 14, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 14, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 14, SYSDATE ,'0:0:0:0:0:0:0:1', '아배고파', 1, 1, 14, 1);     
    

INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 15, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 15, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 15, SYSDATE ,'0:0:0:0:0:0:0:1', '저 곡 올렸어요', 1, 1, 15, 1);     
    

-- 음악 게시물 기초 데이터
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목1', '동물1', 'animal1.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목2', '동물2', 'animal1.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목3', '동물3', 'animal1.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
       (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목4', '동물4', 'animal1.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목5', '동물5', 'animal2.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목6', '', 'animal2.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
       (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목7', '', 'animal2.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
      (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목8', '', 'animal2.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
       (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목9', '', 'animal3.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
     (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목10', '', 'animal3.jpg', 'finalServer\\img',1);
INSERT INTO MUSIC
        (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목11', '', 'animal4.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목12', '', 'animal4.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목13', '', 'animal5.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
       (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목14', '', 'animal5.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목15', '', 'animal5.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목16', '', 'animal6.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
     (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목17', '', 'animal7.jpg', 'finalServer\\img', 1);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목18', '', 'animal8.jpg', 'finalServer\\img', 1);
    INSERT INTO MUSIC
      (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목19', '', 'defaultImage.jpg', 'finalServer\\img', 0);
INSERT INTO MUSIC
    (MUSIC_NO, EMAIL, MUSIC_TITLE, IMG_ORIGIN, IMG_FILESYSTEM, IMG_PATH, HAS_THUMBNAIL)
VALUES
    (MUSIC_SEQ.NEXTVAL, 'admin@web.com', '관리자제목20', '', 'defaultImage.jpg', 'finalServer\\img', 0);

 
    

-- 로그 기초데이터

    INSERT INTO ACTIVE_LOG
    (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 1);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 2);

    INSERT INTO ACTIVE_LOG
     (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 3);

    INSERT INTO ACTIVE_LOG
     (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 4);

    INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 5);
   
        INSERT INTO ACTIVE_LOG
    (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 6);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 7);

    INSERT INTO ACTIVE_LOG
     (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 8);

    INSERT INTO ACTIVE_LOG
     (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 9);

    INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 10);
        INSERT INTO ACTIVE_LOG
    (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 11);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 12);

    INSERT INTO ACTIVE_LOG
     (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 13);

    INSERT INTO ACTIVE_LOG
     (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 14);

    INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 15);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 16);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 17);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 18);
            INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 19);
        INSERT INTO ACTIVE_LOG
      (ACTIVE_NO, EMAIL, MUSIC_NO)
VALUES
    (ACTIVE_LOG_SEQ.NEXTVAL, 'admin@web.com', 20);


INSERT INTO PASS
    (PASS_NO, PASS_NAME, PASS_PRICE)
VALUES 
    (PASS_SEQ.NEXTVAL, '30일이용권', 8900);
INSERT INTO PASS
    (PASS_NO, PASS_NAME, PASS_PRICE)
VALUES 
    (PASS_SEQ.NEXTVAL, '정액이용권', 7500);

COMMIT;