INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'abc111@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '거북이와두루미', '김종수', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
    
    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'o2of782@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '코딩하는 사람', '김수형', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
        
    
    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'qirfasdfi@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '할리스에있는사람', '김할리', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
        
    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'dondaond44@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '노란색옷입은사람', '김나영', 'No', '01088888888', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
       
       
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'dondd44@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '빨간색 옷 입은 사람', '김대박', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
        
        
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'dondfage7852@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '크리스마스에솔로인사람', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
        
        
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'eifdaq1231322@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '솔로가진짜인사람', '김모임', 'No', '01099668578', null, null, null, null, null, null, null, 4, null, sysdate, null, null, null, null);
        
        
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'ei54efd22@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'Ditto', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
                                    
        
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'banban@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'Deetoo', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
                                    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'newnewban@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'Banheesu', '반희수', 'No', '01099668578', null, null, null, null, null, null, null, 2, null, sysdate, null, null, null, null);
          
                                    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'aespa156489@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '카리나팬인사람', '임플랜', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
             
                                    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'aes4156pa159@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '겨울하면윈터지', '임겨울', 'No', '01099668578', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
 
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'aedfae7pa159@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '굶주린사자', '강고양', 'F', '01099668578', null, null, null, null, null, null, null, 1, null, sysdate, null, null, null, null);
   
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'omorw722@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '에어팟 한 쪽 없는 사람', '송소내', 'F', '01084498578', null, null, null, null, null, null, null, 2, null, sysdate, null, null, null, null);
              
              
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'o752322@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '에어팟 두 쪽 있는 사람', '엄희라', 'F', '01084498578', null, null, null, null, null, null, null, 4, null, sysdate, null, null, null, null);
     
              
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'eeodsp45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '스파이일 수도 있는 사람', '김무비', 'F', '01089675578', null, null, null, null, null, null, null, 3, null, sysdate, null, null, null, null);
     

              
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'eeo781p45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '뉴진스 여섯번째 멤버', '이혜원', 'F', '01085745578', null, null, null, null, null, null, null, 1, null, sysdate, null, null, null, null);
     

INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, '852qwd45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '뉴진스새멤버', '김민지', 'F', '01075145578', null, null, null, null, null, null, null, 3, null, sysdate, null, null, null, null);
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'aa852qwd45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'new진수', '반희수', 'F', '01075141254', null, null, null, null, null, null, null, 2, null, sysdate, null, null, null, null);
     
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'asdxczd45@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '뉴jeans스', '반희수', 'F', '01075141254', null, null, null, null, null, null, null, 3, null, sysdate, null, null, null, null);
     

INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'asfvarv8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'sayit디도', '이해린', 'F', '01075141254', null, null, null, null, null, null, null, 2, null, sysdate, null, null, null, null);
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, '748v8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', 'sayitback', '김바란', 'F', '0107557954', null, null, null, null, null, null, null, 1, null, sysdate, null, null, null, null);
     

INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, '785qsdv8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '고오고오고', '김고오', 'F', '0107557954', null, null, null, null, null, null, null, 3, null, sysdate, null, null, null, null);
     
     
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, '7qdsadjdv8@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '디도말해', '반희수', 'F', '0107557954', null, null, null, null, null, null, null, 1, null, sysdate, null, null, null, null);
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'whatwhat1@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '아이즈원시퀀스', '장원영', 'F', '0107557954', null, null, null, null, null, null, null, 2, null, sysdate, null, null, null, null);
     
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'whay1@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '문을열어봐', '장원영', 'F', '0107557954', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'ekfasdf7521@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '댓어시퀀스', '김채원', 'F', '0107557954', null, null, null, null, null, null, null, 3, null, sysdate, null, null, null, null);
    
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'ge5df7521@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '조용하지마!', '유나', 'F', '0107557954', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);

INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'g857521@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '강혜원입니다', '강혜원', 'F', '0107557954', null, null, null, null, null, null, null, 2, null, sysdate, null, null, null, null);
   
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'smail21@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '항상웃자!', '최예나', 'F', '01095244832', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
   
INSERT INTO USERS
    (USER_NO, EMAIL, PW, ARTIST, NAME, GENDER, MOBILE, BIRTHYEAR, BIRTHDAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, AGREE_CODE, SNS_TYPE, JOIN_DATE, PW_MODIFY_DATE, INFO_MODIFY_DATE, SESSION_ID, SESSION_LIMIT_DATE)
VALUES
    (USERS_SEQ.NEXTVAL, 'panorama@web.com', ' FFE1ABD1A 8215353C233D6E0 9613E95EEC4253832A761AF28FF37AC5A15 C', '이건..운명', '야부키', 'F', '01095244832', null, null, null, null, null, null, null, 0, null, sysdate, null, null, null, null);
   



   


INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 18, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 18, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 18, SYSDATE ,'0:0:0:0:0:0:0:1', '안녕하세요', 1, 1, 18, 5);  
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 18, SYSDATE ,'0:0:0:0:0:0:0:1', '어제 데뷔한', 1, 1, 18, 4);  
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 18, SYSDATE ,'0:0:0:0:0:0:0:1', '신입입니다', 1, 1, 18, 3); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 18, SYSDATE ,'0:0:0:0:0:0:0:1', '잘 부탁드립니다!', 1, 1, 18, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 18, SYSDATE ,'0:0:0:0:0:0:0:1', ':D', 1, 1, 18, 1);    
    



INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 19, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 19, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 19, SYSDATE ,'0:0:0:0:0:0:0:1', '태그뮤직 예쁘네요', 1, 1, 19, 3); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 19, SYSDATE ,'0:0:0:0:0:0:0:1', '아주 멋져요', 1, 1, 19, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 19, SYSDATE ,'0:0:0:0:0:0:0:1', '갖고 싶어요 ㅎㅎ', 1, 1, 19, 1); 
    






INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 21, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 21, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 21, SYSDATE ,'0:0:0:0:0:0:0:1', '팔을 좀 더 길게 뻗어도 ', 1, 1, 21, 2); 
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 21, SYSDATE ,'0:0:0:0:0:0:0:1', '뒷꿈치 어쩌고 ', 1, 1, 21, 1);     
    
    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 22, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 22, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 22, SYSDATE ,'0:0:0:0:0:0:0:1', 'You keep me wrapped around your finger', 1, 1, 22, 2);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 22, SYSDATE ,'0:0:0:0:0:0:0:1', 'Wrapped around your finger', 1, 1, 22, 1);   
    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 23, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 23, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 23, SYSDATE ,'0:0:0:0:0:0:0:1', 'Why do I tell myself that I will do the best I can?', 1, 1, 23, 1); 
    
    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 24, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 15, 0);    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 24, SYSDATE ,'0:0:0:0:0:0:0:1', 'Then was shot back down to Earth', 1, 1, 15, 1);   
    
    
    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 25, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 25, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 25, SYSDATE ,'0:0:0:0:0:0:0:1', 'Ooh, covered in carats', 1, 1, 25, 2);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 25, SYSDATE ,'0:0:0:0:0:0:0:1', 'Ooh, but then you just vanished', 1, 1, 25, 1);   
    
    
    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 27, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 27, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 27, SYSDATE ,'0:0:0:0:0:0:0:1', 'Got a hundred big faces, but I am still alone', 1, 1, 27, 2);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 27, SYSDATE ,'0:0:0:0:0:0:0:1', 'Ayy, I would throw it all away', 1, 1, 27, 1);     
    
    
    
    
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 29, SYSDATE ,'0:0:0:0:0:0:0:1', NULL, 1, 0, 29, 0);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 29, SYSDATE ,'0:0:0:0:0:0:0:1', 'I would throw it all away', 1, 1, 29, 2);
INSERT INTO CHAT_ADMIN
    (CHAT_NO, USER_NO, CHAT_DATE, IP, CONTENT, STATE, DEPTH, GROUP_NO, GROUP_ORDER)
VALUES
    (CHAT_SEQ.NEXTVAL, 29, SYSDATE ,'0:0:0:0:0:0:0:1', 'I just keep on wishin that the money made you stay', 1, 1, 29, 1);      


COMMIT; 